server:
  port: 8083

spring:
  application:
    name: service-passenger-user

  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/service-passenger-user?characterEncoding=utf-8&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver