server:
  port: 8081

spring:
  application:
    name: api-passenger
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0